### ISSUE TITLE
support collectors with different ports

### ISSUE THREAD

**Issue by MDSharma** [smitmartijn/roneo-netflow-duplicator#4]
Hi,
Wondering if this can support multiple collectors running at different ports.. 

for e.g. (standard config):

```
bind_ip: 10.0.0.2
bind_port: 2055

collectors:
  - 10.0.0.10
  - 10.0.0.11
  - 10.0.0.12
collector_port: 2055

debug: False
log_file: /var/log/roneo.log
```
.. vs config that can support various port numbers

```
collectors:
  - 10.0.0.10:2055
  - 10.0.0.11:8888
  - 10.0.0.12:9312
```
or similar?

**Comment by smitmartijn** [comment]
Not at this time, the collector_port is used universally. NetFlow collectors typically run on 2055 - why would you change it?
