### ISSUE TITLE
collector in different subnet to roneo

### ISSUE THREAD

**Issue by micruzz82** [smitmartijn/roneo-netflow-duplicator#6]
Hi @smitmartijn 

Due to our network restrictions, I need to place roneo in 1 subnet which is the oob subnet to the netflow devices.. and the collectors ( for security reason) are placed in a separate subnet.

Per your documentation it states: "For the spoofing to work, it's important to place Roneo in the same IP subnet as the collectors."

Can you please advise if the limitation is that the source device sending the netflow data will not be visibly with the correct IP on the collector after it is forwarded by roneo?

**Comment by smitmartijn** [comment]
Little late 😅 - but networking TCP/IP concepts generally prevent a host to send out traffic that doesn't originate from its own IP address. Roneo spoofs the ESXi host addresses to the collectors, which would be blocked by your routes/firewalls if you don't put it in the same subnet.
