### ISSUE TITLE
Regarding configuration file

### ISSUE THREAD

**Issue by db-vmw** [smitmartijn/roneo-netflow-duplicator#7]
Hi @smitmartijn ,
Thanks for this wonderful project. 

Question on the configuration file:

- What is _bind address_ referring to? Is this the IP of an ESXi host in case of VDS? If so, how do we provide more than one ESXi hosts from where the NETFLOW are to be collected? 
- What is collectors referring to?  Is it the address of the server where we want the NETFLOW packets to be forwarded to? Example: vRNI Collector VMs?  

I am looking to populate the configuration file to forward VDS from a vCenter having multiple ESXi hosts to different vRNI collectors.

Thanks,
Dinesh

**Comment by smitmartijn** [comment]
Hi @db-vmw 

> * What is _bind address_ referring to? Is this the IP of an ESXi host in case of VDS? If so, how do we provide more than one ESXi hosts from where the NETFLOW are to be collected?

It's the IP address the service should bind to. So the IP of the VM you're running this on, and having ESXi hosts send netflow to.

> * What is collectors referring to?  Is it the address of the server where we want the NETFLOW packets to be forwarded to? Example: vRNI Collector VMs?

The collectors that should receive the netflow after Roneo duplicates it. So yes, in your case the vRNI Collectors.
